// <auto-generated />
using System;
using DocumentHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260111003954_AddWorkProgressMonthsYears")]
    partial class AddWorkProgressMonthsYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DocumentHub.Model.ConstructionStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConstructionStaff");
                });

            modelBuilder.Entity("DocumentHub.Model.IncomingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConstructionStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceivingOfficerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SignerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionStaffId");

                    b.HasIndex("ReceivingOfficerId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SignerId");

                    b.ToTable("IncomingDocuments");
                });

            modelBuilder.Entity("DocumentHub.Model.OutgoingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConstructionStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceivingOfficerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SignerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionStaffId");

                    b.HasIndex("ReceivingOfficerId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SignerId");

                    b.ToTable("OutgoingDocuments");
                });

            modelBuilder.Entity("DocumentHub.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DocumentHub.Model.ReceivingOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReceivingOfficers");
                });

            modelBuilder.Entity("DocumentHub.Model.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("DocumentHub.Model.Signer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Signers");
                });

            modelBuilder.Entity("DocumentHub.Model.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityAnswer1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityAnswer2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityQuestion1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityQuestion2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("DocumentHub.Model.WorkProgressMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkProgressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkProgressId");

                    b.ToTable("WorkProgressMonths");
                });

            modelBuilder.Entity("DocumentHub.Model.WorkProgressYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkProgressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkProgressId");

                    b.ToTable("WorkProgressYears");
                });

            modelBuilder.Entity("DocumentHub.ViewModel.WorkProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is3Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is9Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeminar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSudden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsYearly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonInChargeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SeminarDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SuddenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearlyCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignerId");

                    b.HasIndex("PersonInChargeId");

                    b.ToTable("WorkProgresses");
                });

            modelBuilder.Entity("DocumentHub.Model.IncomingDocument", b =>
                {
                    b.HasOne("DocumentHub.Model.ConstructionStaff", "ConstructionStaff")
                        .WithMany()
                        .HasForeignKey("ConstructionStaffId");

                    b.HasOne("DocumentHub.Model.ReceivingOfficer", "ReceivingOfficer")
                        .WithMany()
                        .HasForeignKey("ReceivingOfficerId");

                    b.HasOne("DocumentHub.Model.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.HasOne("DocumentHub.Model.Signer", "Signer")
                        .WithMany()
                        .HasForeignKey("SignerId");

                    b.Navigation("ConstructionStaff");

                    b.Navigation("ReceivingOfficer");

                    b.Navigation("Recipient");

                    b.Navigation("Signer");
                });

            modelBuilder.Entity("DocumentHub.Model.OutgoingDocument", b =>
                {
                    b.HasOne("DocumentHub.Model.ConstructionStaff", "ConstructionStaff")
                        .WithMany()
                        .HasForeignKey("ConstructionStaffId");

                    b.HasOne("DocumentHub.Model.ReceivingOfficer", "ReceivingOfficer")
                        .WithMany()
                        .HasForeignKey("ReceivingOfficerId");

                    b.HasOne("DocumentHub.Model.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId");

                    b.HasOne("DocumentHub.Model.Signer", "Signer")
                        .WithMany()
                        .HasForeignKey("SignerId");

                    b.Navigation("ConstructionStaff");

                    b.Navigation("ReceivingOfficer");

                    b.Navigation("Recipient");

                    b.Navigation("Signer");
                });

            modelBuilder.Entity("DocumentHub.Model.WorkProgressMonth", b =>
                {
                    b.HasOne("DocumentHub.ViewModel.WorkProgress", "WorkProgress")
                        .WithMany()
                        .HasForeignKey("WorkProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkProgress");
                });

            modelBuilder.Entity("DocumentHub.Model.WorkProgressYear", b =>
                {
                    b.HasOne("DocumentHub.ViewModel.WorkProgress", "WorkProgress")
                        .WithMany()
                        .HasForeignKey("WorkProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkProgress");
                });

            modelBuilder.Entity("DocumentHub.ViewModel.WorkProgress", b =>
                {
                    b.HasOne("DocumentHub.Model.Person", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignerId");

                    b.HasOne("DocumentHub.Model.Person", "PersonInCharge")
                        .WithMany()
                        .HasForeignKey("PersonInChargeId");

                    b.Navigation("Assigner");

                    b.Navigation("PersonInCharge");
                });
#pragma warning restore 612, 618
        }
    }
}
